blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (
    HomePageView,
    BlogListView,
    BlogCreateView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
    toggle_activity,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("blog/", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("blog/create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<slug:slug>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/update/<slug:slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/delete/<slug:slug>/", BlogDeleteView.as_view(), name="blog_delete"),
    path("blog/toggle_activity/<slug:slug>/", toggle_activity, name="toggle_activity"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
    path("subscriptions/", include("subsciptions.urls", namespace="subscriptions")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

subsciptions/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from subsciptions.apps import SubsciptionsConfig
from subsciptions.views import (
    SubscriptionDeleteView,
    SubscriptionListView,
    CancelView,
    SuccessView,
    CreateCheckoutSessionView,
    BlogCheckoutPageView,
    StripeIntentView,
    stripe_webhook,
    SubscriptionCreateView,
)

app_name = SubsciptionsConfig.name


urlpatterns = [
    path(
        "subscription-create/<slug:slug>/",
        SubscriptionCreateView.as_view(),
        name="subscription_create",
    ),
    path(
        "subscription-cancel/<slug:slug>/",
        SubscriptionDeleteView.as_view(),
        name="subscription_delete",
    ),
    path(
        "subscription-list/",
        cache_page(60)(SubscriptionListView.as_view()),
        name="subscription_list",
    ),
    path("cancel/", CancelView.as_view(), name="cancel"),
    path("success/<slug:slug>/", SuccessView.as_view(), name="success"),
    path(
        "create-checkout-session/<slug:slug>/",
        CreateCheckoutSessionView.as_view(),
        name="create-checkout-session",
    ),
    path("", BlogCheckoutPageView.as_view(), name="checkout-page"),
    path(
        "create-payment-intent/<int:pk>/",
        StripeIntentView.as_view(),
        name="create-payment-intent",
    ),
    path("webhooks/stripe/", stripe_webhook, name="stripe-webhook"),
]

users/urls.py
from django.contrib.auth.views import LogoutView

from django.urls import path

from users.views import (
    RegisterView,
    CustomLoginView,
    CustomPasswordResetView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
    ProfileUpdateView,
)
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path("", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileUpdateView.as_view(), name="profile"),
    path("password/reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path(
        "password/reset/confirm/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/complete/",
        CustomPasswordResetCompleteView.as_view(),
        name="password_reset_done",
    ),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from transliterate import translit

# Create your models here.
NULLABLE = {"null": True, "blank": True}


class Comment(models.Model):
    comment = models.TextField(verbose_name="Comment")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="User"
    )
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created date")

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.comment


class Blog(models.Model):
    title = models.CharField(max_length=255, verbose_name="Title")
    slug = models.SlugField(max_length=255, verbose_name="Slug", unique=True)
    image = models.ImageField(upload_to="blog/", **NULLABLE, verbose_name="Image")
    description = models.TextField(verbose_name="Description", **NULLABLE)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_date = models.DateTimeField(
        auto_now=True, verbose_name="Updated at", **NULLABLE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="User",
        **NULLABLE
    )
    published_on = models.BooleanField(default=False, verbose_name="Published on")
    views = models.IntegerField(default=0, verbose_name="Views", **NULLABLE)
    price = models.IntegerField(default=0, verbose_name="Price")
    is_paid = models.BooleanField(default=False, verbose_name="Is paid")
    comments = models.ManyToManyField(Comment, verbose_name="Comments", blank=True)

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blogs"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Save the object with an automatically generated slug if none is provided.

        Parameters:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        if not self.slug:
            transliterated_title = translit(self.title, "ru", reversed=True)
            self.slug = slugify(transliterated_title, allow_unicode=True)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"slug": self.slug})

    def toggle_published(self):
        """
        Toggles the published status of the object and saves the changes.
        """
        self.published_on = not self.published_on
        self.save()

blog/forms.py
from django import forms

from blog.models import Blog, Comment
from users.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ["title", "description", "image", "price", "is_paid", "published_on"]
        exclude = ["user", "slug", "comment", "views"]


class CommentForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)

from blog.forms import BlogForm, CommentForm
from blog.models import Blog, Comment
from subsciptions.models import Subscription


# Create your views here.


class HomePageView(TemplateView):
    template_name = "blog/home.html"

    def get_context_data(self, **kwargs):
        """
        Generate context data for the view with information about blogs.

        Parameters:
            **kwargs (dict): Additional keyword arguments.

        Returns:
            dict: A dictionary containing context data for the view.
        """
        context_data = super().get_context_data(**kwargs)
        context_data["blog"] = Blog.objects.filter(published_on=True).order_by("?")[:3]

        if self.request.user.is_authenticated:
            user = self.request.user

            subscribed_blog_ids = Subscription.objects.filter(
                user=user, status=True
            ).values_list("blog__id", flat=True)

            unsubscribed_blogs = Blog.objects.filter(published_on=True).exclude(
                id__in=subscribed_blog_ids
            )
            subscribed_blogs = Blog.objects.filter(
                id__in=subscribed_blog_ids, published_on=True
            )

            context_data["unsubscribed_blogs"] = unsubscribed_blogs
            context_data["subscribed_blogs"] = subscribed_blogs

        return context_data


class BlogListView(LoginRequiredMixin, ListView):
    template_name = "blog/blog_list.html"
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(published_on=True)
        return queryset


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save(commit=False)
            blog.user = self.request.user
            blog.save()
            return super().form_valid(form)
        else:
            return super().form_invalid(form)


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    form_class = CommentForm

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.views += 1
        obj.save()
        return obj

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["comments"] = Comment.objects.filter(blog=self.get_object())
        return context_data

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_content = form.cleaned_data["comment"]
            comment = Comment.objects.create(
                user=self.request.user, comment=comment_content
            )

            blog = self.get_object()
            blog.comments.add(comment)
            blog.save()
            return HttpResponseRedirect(self.request.path_info)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")


def toggle_activity(slug):
    """
    Переключает атрибут 'published_on' объекта Blog.

    Args:
        request (HttpRequest): Объект HTTP-запроса.
        slug (str): Слаг объекта Blog.

    Returns:
        HttpResponseRedirect: Перенаправляет на страницу деталей объекта Blog.
    """
    record_item = get_object_or_404(Blog, slug=slug)
    record_item.toggle_published()
    # return HttpResponseRedirect(request.path_info)
    # return redirect(reverse("blog:blog_detail", args=[record_item.slug]))

blog/templates/blog/includes/inc_main_menu.html
<div class="container-fluid text-center py-3">
    <a class="btn" style="font-size: 25px; color: black; text-shadow: #1b1b1b;" href="{% url 'blog:home' %}">Платформа для публикации контента</a>
</div>
<div class="col d-flex justify-content-start">

    {% if user.is_authenticated %}
         <a class="p-2 btn btn-outline-dark" href="{% url 'users:profile' %}">
             {% if user.avatar %}
             <img src="{{ user.avatar.url }}" alt="Avatar" style="width: 30px; height: 30px; border-radius: 50%;">
             {% endif %}
            Профиль
        </a>
    <form method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <button type="submit" class="p-2 btn btn-outline-dark">Выйти</button>
    </form>
    {% else %}
        <a class="p-2 btn btn-outline-dark" href="{% url 'users:register' %}">Регистрация</a>
    <a class="p-2 btn btn-outline-dark" href="{% url 'users:login' %}">Войти</a>
    {% endif %}

</div>

<div class="col d-flex justify-content-center align-items-center">
    <div class="dropdown">
        <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Меню
        </button>
         {% if user.is_authenticated %}
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'blog:blog_list' %}">Блог</a>
            <a class="dropdown-item" href="{% url 'subscriptions:subscription_list' %}">Подписки</a>
        </div>
         {% endif %}




    </div>
</div>

<div class="col d-flex justify-content-end align-items-center">
    <a class="text-muted" href="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">
            <circle cx="10.5" cy="10.5" r="7.5"></circle>
            <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
        </svg>
    </a>
     {% if user.is_authenticated %}
    <a class="p-2 btn btn-outline-dark" href="{% url 'blog:blog_list' %}">Блог</a>
    <a class="p-2 btn btn-outline-dark" href="{% url 'subscriptions:subscription_list' %}">Подписки</a>
    {% endif %}
</div>

<style>
    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-toggle {
        border: 1px solid #ccc;
        border-radius: 20px;
        display: inline-block;
        padding: 10px 20px;
        cursor: pointer;
        background-color: #fff;
        transition: all 0.3s ease-in-out;
    }

    .dropdown-toggle:hover {
        transform: translateY(-3px);
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
    }

    .dropdown-toggle:active {
        transform: translateY(-1px);
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }

    .dropdown-menu {
        position: absolute;
        top: 100%;
        left: 0;
        z-index: 1000;
        display: none;
        float: left;
        min-width: 10rem;
        padding: .10rem 10px;
        margin: .125rem 0 0;
        font-size: 1rem;
        color: #212529;
        text-align: left;
        list-style: none;
        background-color: #fff;
        background-clip: border-box;
        border: 1px solid rgba(0, 0, 0, .15);
        border-radius: 15px 15px;
        transform: translateY(-1px);
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }

    .dropdown:hover .dropdown-menu {
        display: block;
        animation: dropdown-fade-in 0.3s ease-in-out forwards;
    }

</style>