blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (
    HomePageView,
    BlogListView,
    BlogCreateView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
    toggle_activity,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("blog/", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("blog/create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<slug:slug>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/update/<slug:slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/delete/<slug:slug>/", BlogDeleteView.as_view(), name="blog_delete"),
    path("blog/toggle_activity/<slug:slug>/", toggle_activity, name="toggle_activity"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
    path("subscriptions/", include("subsciptions.urls", namespace="subscriptions")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

subsciptions/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from subsciptions.apps import SubsciptionsConfig
from subsciptions.views import (
    SubscriptionDeleteView,
    SubscriptionListView,
    CancelView,
    SuccessView,
    CreateCheckoutSessionView,
    BlogCheckoutPageView,
    StripeIntentView,
    stripe_webhook,
    SubscriptionCreateView,
)

app_name = SubsciptionsConfig.name


urlpatterns = [
    path(
        "subscription-create/<slug:slug>/",
        SubscriptionCreateView.as_view(),
        name="subscription_create",
    ),
    path(
        "subscription-cancel/<slug:slug>/",
        SubscriptionDeleteView.as_view(),
        name="subscription_delete",
    ),
    path(
        "subscription-list/",
        cache_page(60)(SubscriptionListView.as_view()),
        name="subscription_list",
    ),
    path("cancel/", CancelView.as_view(), name="cancel"),
    path("success/<slug:slug>/", SuccessView.as_view(), name="success"),
    path(
        "create-checkout-session/<slug:slug>/",
        CreateCheckoutSessionView.as_view(),
        name="create-checkout-session",
    ),
    path("", BlogCheckoutPageView.as_view(), name="checkout-page"),
    path(
        "create-payment-intent/<int:pk>/",
        StripeIntentView.as_view(),
        name="create-payment-intent",
    ),
    path("webhooks/stripe/", stripe_webhook, name="stripe-webhook"),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from transliterate import translit

# Create your models here.
NULLABLE = {"null": True, "blank": True}


class Comment(models.Model):
    comment = models.TextField(verbose_name="Comment")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="User"
    )
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created date")

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.comment


class Blog(models.Model):
    title = models.CharField(max_length=255, verbose_name="Title")
    slug = models.SlugField(max_length=255, verbose_name="Slug", unique=True)
    image = models.ImageField(upload_to="blog/", **NULLABLE, verbose_name="Image")
    description = models.TextField(verbose_name="Description", **NULLABLE)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_date = models.DateTimeField(
        auto_now=True, verbose_name="Updated at", **NULLABLE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="User",
        **NULLABLE
    )
    published_on = models.BooleanField(default=False, verbose_name="Published on")
    views = models.IntegerField(default=0, verbose_name="Views", **NULLABLE)
    price = models.IntegerField(default=0, verbose_name="Price")
    is_paid = models.BooleanField(default=False, verbose_name="Is paid")
    comments = models.ManyToManyField(Comment, verbose_name="Comments", blank=True)

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blogs"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Save the object with an automatically generated slug if none is provided.

        Parameters:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        if not self.slug:
            transliterated_title = translit(self.title, "ru", reversed=True)
            self.slug = slugify(transliterated_title, allow_unicode=True)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"slug": self.slug})

    def toggle_published(self):
        """
        Toggles the published status of the object and saves the changes.
        """
        self.published_on = not self.published_on
        self.save()

blog/forms.py
from django import forms

from blog.models import Blog, Comment
from users.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ["title", "description", "image", "price", "is_paid", "published_on"]
        exclude = ["user", "slug", "comment", "views"]


class CommentForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)

from blog.forms import BlogForm, CommentForm
from blog.models import Blog, Comment
from subsciptions.models import Subscription


# Create your views here.


class HomePageView(TemplateView):
    template_name = "blog/home.html"

    def get_context_data(self, **kwargs):
        """
        Generate context data for the view with information about blogs.

        Parameters:
            **kwargs (dict): Additional keyword arguments.

        Returns:
            dict: A dictionary containing context data for the view.
        """
        context_data = super().get_context_data(**kwargs)
        context_data["blog"] = Blog.objects.filter(published_on=True).order_by("?")[:3]

        if self.request.user.is_authenticated:
            user = self.request.user

            subscribed_blog_ids = Subscription.objects.filter(
                user=user, status=True
            ).values_list("blog__id", flat=True)

            unsubscribed_blogs = Blog.objects.filter(published_on=True).exclude(
                id__in=subscribed_blog_ids
            )
            subscribed_blogs = Blog.objects.filter(
                id__in=subscribed_blog_ids, published_on=True
            )

            context_data["unsubscribed_blogs"] = unsubscribed_blogs
            context_data["subscribed_blogs"] = subscribed_blogs

        return context_data


class BlogListView(LoginRequiredMixin, ListView):
    template_name = "blog/blog_list.html"
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(published_on=True)
        return queryset


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save(commit=False)
            blog.user = self.request.user
            blog.save()
            return super().form_valid(form)
        else:
            return super().form_invalid(form)


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    form_class = CommentForm

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.views += 1
        obj.save()
        return obj

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["comments"] = Comment.objects.filter(blog=self.get_object())
        return context_data

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_content = form.cleaned_data["comment"]
            comment = Comment.objects.create(
                user=self.request.user, comment=comment_content
            )

            blog = self.get_object()
            blog.comments.add(comment)
            blog.save()
            return HttpResponseRedirect(self.request.path_info)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")


def toggle_activity(slug):
    """
    Переключает атрибут 'published_on' объекта Blog.

    Args:
        request (HttpRequest): Объект HTTP-запроса.
        slug (str): Слаг объекта Blog.

    Returns:
        HttpResponseRedirect: Перенаправляет на страницу деталей объекта Blog.
    """
    record_item = get_object_or_404(Blog, slug=slug)
    record_item.toggle_published()
    # return HttpResponseRedirect(request.path_info)
    # return redirect(reverse("blog:blog_detail", args=[record_item.slug]))

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Рассылка</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
</head>


<body>

<header class="blog-header py-3 d-flex justify-content-center align-items-center h-100">
    <div class="container">
        <div class="row">
            {% include 'blog/includes/inc_main_menu.html' %}
        </div>
    </div>
</header>
<div class="container">
    <div class="row p-5 justify-content-lg-center">
        {% block content %}
        {% endblock %}
    </div>
</div>

</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
        <h2 class="mt-4 mb-4 text-center">Подтвердите удаление</h2>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data" class="mt-3">
                            {% csrf_token %}
                            <p>
                                Вы уверены, что хотите удалить "{{ object.title }}"?
                            </p>
                            <div class="row justify-content-center">
                                <a href="{% url 'blog:home' %}" class="btn btn-secondary mr-3">Вернуться на
                                    главную</a>
                                <button class="btn btn-danger" type="submit">Удалить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .card {
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
            width: 100%;

        }

        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}

{% block content %}
{% load my_tags %}
<div class="container">
    <div class="card text-center">
        <div class="card-header">
            {{ object.title }}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ object.description }}</h5>
            <img src="{% mediapath object.image %}" class="card-img-top mx-auto d-block img-fluid" alt=""
                 style="width: auto; height: auto;">
            <p class="card-text">Просмотры: {{ object.views }}</p>


            <h3>Комментарии</h3>
            <div class="comment-section">
                <div class="comments-container">
                    {% for comment in comments %}
                    <div class="comment">
                        <h5 class="card-title">
                            {% if comment.user.avatar %}
                            <img src="{{ comment.user.avatar.url }}" alt="Avatar"
                                 style="width: 30px; height: 30px; border-radius: 50%;">
                            {% endif %}
                            ({{ comment.user }})
                        </h5>
                        <h6>{{ comment.comment }}</h6>
                        <p>{{ comment.created_date|date:"F d, Y H:i" }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <form method="post" enctype="multipart/form-data" class="comment-form">
                {% csrf_token %}
                <textarea name="comment" rows="4" cols="50" class="comment-input"
                          placeholder="Напишите комментарий"></textarea>
                <button class="btn btn-info" type="submit">Оставить комментарий</button>
            </form>


            {% if object.user == user %}
            <a href="{% url 'blog:blog_update' object.slug %}" class="btn btn-warning">Изменить
                запись</a>
            {% endif %}
            {% if object.user == user %}
            <a href="{% url 'blog:blog_delete' object.slug %}" class="btn btn-danger">Удалить
                запись</a>
            {% endif %}
            <br><br>
            <a href="{% url 'subsciptions:subscription_list' %}" class="btn btn-secondary">Мой контент</a>
            {% if object.user == user %}
            {% if object.published_on %}
            <a href="{% url 'blog:toggle_activity' object.slug %}" class="btn btn-outline-danger">Снять с
                публикации</a>
            {% else %}
            <a href="{% url 'blog:toggle_activity' object.slug %}" class="btn btn-outline-primary">Опубликовать</a>
            {% endif %}
            {% endif %}
        </div>
        <div class="card-footer text-muted">
            <p class="card-text">
                Создана: {{ object.created_date }}<br>
                Опубликована: {{ object.published_on }}
            </p>
        </div>
    </div>
</div>

<style>
    .card {
        margin-top: 20px;
        border: 1px solid #ddd;
        border-radius: 5px;
        box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
    }

    .card-header {
        font-size: 24px;
        background-color: #eee;
        font-weight: bold;
    }

    .card-body {
        text-align: center;
    }

    .card-text {
        font-size: 18px;
    }

    .btn {
        padding: 10px 20px;
        border-radius: 20px;
        cursor: pointer;
        transition: all 0.3s ease-in-out;
    }

    .btn:hover {
        transform: translateY(-3px);
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
    }

    .btn:active {
        transform: translateY(-1px);
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }

    .comment-section {
        border: 1px solid #ccc; /* Рамка вокруг секции комментариев */
        border-radius: 5px;
        padding: 10px;
        max-height: 300px; /* Максимальная высота секции, добавляет прокрутку при необходимости */
        overflow-y: auto; /* Включает вертикальную прокрутку при необходимости */
    }

    .comments-container {
        max-height: 100%; /* Занимает максимально доступное пространство */
        padding: 10px;
    }

    .comment {
        border: 1px solid #ddd; /* Рамка вокруг каждого комментария */
        border-radius: 5px;
        padding: 5px;
        margin-bottom: 10px;
        background-color: #eedabe; /* Фон комментария */
    }

    .comment-form {
        max-width: 600px; /* Устанавливаем максимальную ширину формы */
        margin: 0 auto; /* Центрируем форму на странице */
        padding: 10px;
        background-color: #f9f9f9; /* Фон формы */
        border: 1px solid #ccc; /* Рамка вокруг формы */
        border-radius: 5px; /* Закругляем углы */
    }

    .comment-input {
        width: 100%; /* Занимаем всю доступную ширину */
        box-sizing: border-box; /* Включаем padding и border в расчет ширины */
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc; /* Рамка вокруг textarea */
        border-radius: 5px; /* Закругляем углы */
    }

    .comment-submit {
        padding: 10px 20px;
        background-color: #007bff; /* Цвет кнопки */
        color: #fff; /* Цвет текста кнопки */
        border: none;
        border-radius: 5px; /* Закругляем углы */
        cursor: pointer;
    }

    .comment-submit:hover {
        background-color: #0056b3; /* Цвет кнопки при наведении */
    }


</style>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-6 col-lg-4 bg-light p-3 rounded">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group text-center">
                                <button class="btn btn-success mt-3" type="submit">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>

        .card {
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
            width: 100%;

        }

        .card-body form {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
        }

        .form-group {
            margin-bottom: 1rem;
            text-align: left;
            padding: 0 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: bold;
        }

        .form-group input[type="time"],
        .form-group input[type="text"],
        .form-group input[type="text"],
        .form-group input[type="text"],
        .form-group input[type="email"] {
            padding: 0.5rem;
            border: none;
            border-radius: 5px;
            background-color: #f1f1f1;
            margin-bottom: 0.5rem;
            width: 100%;
            box-sizing: border-box;
        }

        .form-group input[type="time"]:focus,
        .form-group input[type="text"]:focus,
        .form-group input[type="text"]:focus,
        .form-group input[type="text"]:focus,
        .form-group input[type="email"]:focus {
            outline: none;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        }

        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}

{% block content %}
{% load my_tags %}


<div class="card flex-md-row mb-4 box-shadow h-md-250">
    <div class="card-body d-flex flex-column align-items-start">
        <div class="card-subtitle mb-auto" id="blog-list">
            {% for object in object_list %}
            {% if object.published_on %}
            {% if user.is_authenticated %}
            <h3 class="mb-0 text-center">
                <a class="text-dark" href="#">{{ object.title }}</a>
            </h3>
            {% endif %}
            <p class="card-text text-center mb-auto">{{ object.description | truncatechars:100 }}</p>
            {% if user.is_authenticated %}

            <div style="filter: blur(50px);">
                <img src="{% mediapath object.image %}"
                     class="card-img-top mx-auto d-block img-fluid" alt=""
                     style="width: auto; height: auto;">
            </div>

            {% endif %}

            <h3 style="text-align: center">Просмотры: {{object.views}}</h3>

            <p class="card-text text-center">
                {% if user.is_authenticated %}
                    {% if object.is_paid or object.price > 0 %}
                        <form class="text-center" action="{% url 'subscriptions:create-checkout-session' object.slug %}" method="post">
                            {% csrf_token %}
                        <input type="submit" class="btn btn-success btn-sm" value="Подписаться {{ object.price }} $">
                        </form>
                    {% else %}
                        <a href="{% url 'subscriptions:subscription_create' object.slug %}" class="btn btn-success btn-sm">Подписаться</a>
                    {% endif %}
                {% endif %}
            </p>

            {% endif %}
            {% endfor %}
        </div>
        <div class="container" style="text-align: center">
        {% if user.is_authenticated %}
        <a href="{% url 'blog:blog_create' %}" class="btn btn-outline-secondary btn-lg my-3"
           style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">
            Создать запись
        </a>
        {% endif %}
    </div>

    </div>
</div>

<style>
    .btn {
        padding: 10px 20px;
        border-radius: 20px;
        cursor: pointer;
        transition: all 0.3s ease-in-out;
    }

    .btn:hover {
        transform: translateY(-3px);
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
    }

    .btn:active {
        transform: translateY(-1px);
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }
</style>

{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% load static %}
{% block content %}
<body>
<div class="container-h text-center my-5 py-5">
    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card mb-4 box-shadow">
                <div class="card-header bg-dark text-white">
                    <h1 class="font-weight-normal">Cервис контента</h1>
                </div>

            </div>
        </div>
    </div>

    <h1>Статьи</h1>

    <div class="container">
        <div class="row">
            {% for item in blog %}
            {% if item.published_on %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <h3 class="card-header bg-dark">
                        {% if item in subscribed_blogs or item.user == user %}
                        <a href="{% url 'blog:blog_detail' item.slug %}"
                           style="color: white; margin: 0;">{{item.title}}</a>
                        {% else %}
                        <a href="#" style="color: white; margin: 0;">{{item.title}}</a>
                        {% endif %}
                    </h3>


                    <div class="card-body">
                        <h5 class="card-title">{{ item.description | truncatechars:100 }}</h5>

                        {% if user.is_authenticated and item in subscribed_blogs or item.user == user %}
                        <img src="{% mediapath item.image %}"
                             class="card-img-top mx-auto d-block img-fluid" alt=""
                             style="width: auto; height: auto;">
                        {% else %}
                        <div style="filter: blur(30px);">
                            <img src="{% mediapath item.image %}"
                                 class="card-img-top mx-auto d-block img-fluid" alt=""
                                 style="width: auto; height: auto;">
                        </div>

                        {% endif %}


                        <h1 class="card-title pricing-card-title">{{ item.price }} $.</h1>
                        {% if user.is_authenticated %}
                            {% if item.user != user %}
                                {% if item in subscribed_blogs %}
                                    <a href="{% url 'subscriptions:subscription_delete' item.slug %}" class="btn btn-danger btn-sm">Отписаться</a>
                                {% elif item in unsubscribed_blogs %}
                                    {% if item.is_paid or item.price > 0 %}
                                        <form action="{% url 'subscriptions:create-checkout-session' item.slug %}" method="post">
                                            {% csrf_token %}
                                            <input type="submit" class="btn btn-success btn-sm" value="Подписаться {{ item.price }} $">
                                        </form>
                                    {% else %}
                                        <a href="{% url 'subscriptions:subscription_create' item.slug %}" class="btn btn-success btn-sm">Подписаться</a>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        {% endif %}



                        <ul>
                            <li><a class="card-text">Просмотры: {{item.views}}</a></li>
                            <li><p class="card-text">Дата публикации: {{ item.created_date }}</p></li>
                        </ul>
                    </div>

                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
</body>
<style>
    .btn {
        margin-top: 5px;
        padding: 10px 20px;
        border-radius: 20px;
        cursor: pointer;
        transition: all 0.3s ease-in-out;
    }

    .btn:hover {
        transform: translateY(-3px);
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
    }

    .btn:active {
        transform: translateY(-1px);
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }

    .container-h {
        background-color: #f7f7f7;
        border: 1px solid #ddd;
        box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }

    .card-header h1 {
        font-size: 2.5rem;
        font-weight: bold;
        letter-spacing: 0.1em;
        margin-bottom: 1rem;
    }

    .card-body {
        font-size: 1.2rem;
        line-height: 1.6;
    }

    ul li {
        margin-bottom: 0.5rem;
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.2);
        transition: all 0.3s ease;
    }
</style>
{% endblock %}