blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (
    HomePageView,
    BlogListView,
    BlogCreateView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
    toggle_activity,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("blog/", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("blog/create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<slug:slug>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/update/<slug:slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/delete/<slug:slug>/", BlogDeleteView.as_view(), name="blog_delete"),
    path("blog/toggle_activity/<slug:slug>/", toggle_activity, name="toggle_activity"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
    path("subscriptions/", include("subsciptions.urls", namespace="subscriptions")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

users/urls.py
from django.contrib.auth.views import LogoutView

from django.urls import path

from users.views import (
    RegisterView,
    CustomLoginView,
    CustomPasswordResetView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
    ProfileUpdateView,
)
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path("", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileUpdateView.as_view(), name="profile"),
    path("password/reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path(
        "password/reset/confirm/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/complete/",
        CustomPasswordResetCompleteView.as_view(),
        name="password_reset_done",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser, UserManager as BaseUserManager
from django.db import models

# Create your models here.

NULLABLE = {"null": True, "blank": True}


class UserManager(BaseUserManager):
    def create_user(self, phone, password, **extra_fields):
        """
        Create a new user with the given phone number, password, and any additional fields.

        Parameters:
            phone (str): The phone number of the user.
            password (str): The password for the user.
            **extra_fields: Additional fields that can be passed to create the user.

        Returns:
            User: The newly created user object.
        """
        if not phone:
            raise ValueError("The phone must be set")
        user = self.model(phone=phone, **extra_fields)
        user.is_active = True
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, password, **extra_fields):
        """
        Creates a superuser with the given phone, password, and any extra fields.

        :param phone: The phone number of the superuser
        :param password: The password for the superuser
        :param **extra_fields: Additional fields for the superuser
        :return: The created superuser
        :raises ValueError: If is_staff or is_superuser is not True
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(phone, password, **extra_fields)


class User(AbstractUser):
    """
    Custom user model for the authentication app.
    """

    objects = UserManager()

    username = models.CharField(
        max_length=50, **NULLABLE, unique=True, verbose_name="Username"
    )
    phone = models.CharField(max_length=25, unique=True, verbose_name="Phone number")
    avatar = models.ImageField(upload_to="users/", **NULLABLE, verbose_name="Avatar")

    USERNAME_FIELD = "phone"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.phone

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

users/forms.py
import re

from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    PasswordResetForm,
    SetPasswordForm,
    UserChangeForm,
    UsernameField,
)
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class CustomUserRegisterForm(StyleFormMixin, UserCreationForm):
    """
    A custom form for registering a new user.
    """

    phone = forms.CharField(
        max_length=12,
        label="Phone number",
        help_text="Enter your phone number",
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "Phone number"}),
    )

    password1 = forms.CharField(
        label="Password",
        help_text="Enter your password",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}),
    )

    password2 = forms.CharField(
        label="Confirm password",
        help_text="Enter your password again",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm password"}),
    )

    class Meta:
        model = User
        fields = ("phone", "password1", "password2")

    def clean_phone(self):
        """
        A method to clean and validate the phone number field.

        Parameters:
            self: the instance of the form
        Returns:
            phone: the cleaned and validated phone number
        """
        phone = self.cleaned_data.get("phone")
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("Phone number already exists")
        elif not re.match(r"^\+7\d{10}$", phone):
            raise forms.ValidationError(
                "Phone number must start with +7 and contain 10 digits"
            )
        return phone

    def save(self, commit=True):
        """
        Save the user data with an option to immediately commit the changes to the database.

        :param commit: A boolean indicating whether to commit the changes to the database immediately. Default is True.
        :return: The user object after saving the data.
        """
        user = super().save(commit=False)
        user.phone = self.cleaned_data["phone"]
        if commit:
            user.save()
        return user


class CustomAuthenticationForm(StyleFormMixin, AuthenticationForm):
    """
    A custom form for authenticating a user.
    """

    username = forms.CharField(
        max_length=12,
        label="Phone number",
        help_text="Enter your phone number",
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "Phone number"}),
    )

    password = forms.CharField(
        label="Password",
        help_text="Enter your password",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}),
    )

    class Meta:
        model = User
        fields = ("phone", "password")


class CustomUserChangeForm(StyleFormMixin, UserChangeForm):
    """
    A custom form for changing user data.
    """

    class Meta:
        model = User
        fields = ("phone", "avatar")
        field_classes = {"username": UsernameField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["password"].widget = forms.HiddenInput()


class CustomPasswordResetForm(StyleFormMixin, PasswordResetForm):
    email = forms.EmailField(
        required=False,
        widget=forms.HiddenInput(),
    )
    phone = forms.CharField(
        max_length=12,
        label="Phone number",
        help_text="Enter your phone number",
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "Phone number"}),
    )

    class Meta:
        model = User
        fields = ("phone",)

    def clean_phone(self):
        """
        A method to clean and validate the phone number field.

        Parameters:
            self: the instance of the form
        Returns:
            phone: the cleaned and validated phone number
        """
        phone = self.cleaned_data.get("phone")
        if not re.match(r"^\+7\d{10}$", phone):
            raise forms.ValidationError(
                "Phone number must start with +7 and contain 10 digits"
            )
        return phone

    def save(self, request, **kwargs):
        """
        Save the user data based on the provided phone number.

        :param request: The request object containing user data.
        :param kwargs: Additional keyword arguments.
        :return: A tuple containing the token and uid generated.
        """
        phone = self.cleaned_data["phone"]
        user = User.objects.get(phone=phone)
        token_generator = kwargs.get("token_generator", default_token_generator)
        token = token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        return token, uid


class CustomResetConfirmForm(StyleFormMixin, SetPasswordForm):
    new_password1 = forms.CharField(
        label="New password",
        help_text="Enter your new password",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "New password"}),
    )

    new_password2 = forms.CharField(
        label="Confirm new password",
        help_text="Enter your new password again",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm new password"}),
    )

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import (
    CustomUserRegisterForm,
    CustomAuthenticationForm,
    CustomPasswordResetForm,
    CustomResetConfirmForm,
    CustomUserChangeForm,
)
from users.models import User


# Create your views here.


class RegisterView(CreateView):
    model = User
    form_class = CustomUserRegisterForm
    success_url = reverse_lazy("users:login")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Register"
        return context

    def form_valid(self, form):
        return super().form_valid(form)


class CustomLoginView(LoginView):
    template_name = "users/login.html"
    form_class = CustomAuthenticationForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Login"
        return context

    def form_valid(self, form):
        return super().form_valid(form)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = CustomUserChangeForm
    success_url = reverse_lazy("blog:home")

    def get_object(self, queryset=None):
        return self.request.user


class CustomPasswordResetView(PasswordResetView):
    template_name = "users/password_reset_form.html"
    form_class = CustomPasswordResetForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Reset password"
        return context

    def form_valid(self, form):
        token, uid = form.save(self.request)
        return redirect("users:password_reset_confirm", token=token, uidb64=uid)


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "users/password_reset_confirm.html"
    form_class = CustomResetConfirmForm
    success_url = reverse_lazy("users:password_reset_done")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Reset password"
        return context


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "users/password_reset_complete.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Reset password"
        return context

users/templates/users/login.html
{% extends 'blog/base.html' %}


{% block content %}
        <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-lg-12">
                <div class="card shadow-sm my-4">
                    <div class="card-header text-center">
                        <h4 class="card-title">Пользователь</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <a class="text-muted" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                            <a class="text-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
                            <div class="form-group text-center">
                                <a href="{% url 'blog:home' %}"
                                   class="btn btn-secondary mt-3">Отменить</a>
                                <button class="btn btn-success mt-3" type="submit">Войти</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>

        .card {
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
            width: 100%;

        }

        .card-body form {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
        }

        .form-group {
            margin-bottom: 1rem;
            text-align: left;
            padding: 0 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: bold;
        }

        .form-group input[type="email"]:focus,
        .form-group input[type="text"]:focus,
        .form-group input[type="text"]:focus {
            outline: none;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        }

        .form-group input[type="email"],
        .form-group input[type="text"],
        .form-group input[type="text"] {
            padding: 0.5rem;
            border: none;
            border-radius: 5px;
            background-color: #f1f1f1;
            margin-bottom: 0.5rem;
            width: 100%;
            box-sizing: border-box;
        }

        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'blog/base.html' %}

{% block content %}
    <div style="display: flex; flex-direction: column; align-items: center; margin: 0 auto;"><h2 class="active">Создан
        новый пароль</h2>
        <a href="{% url 'users:login' %}" class="btn btn-link">
            Войти заново
        </a>
    </div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-6 col-lg-4 bg-light p-3 rounded">
                <div class="card shadow-sm">
                    <div class="card-header text-center">
                        <h4 class="card-title">Пароль</h4>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h1 class="h3 mb-3 fw-normal">Введите новый пароль</h1>
                            <div class="form-group text-center">
                                {{ form.as_p }}
                                <button class="p-2 btn btn-outline-success" type="submit">Сохранить</button>
                                <div class="form-group text-center">
                                    <a class="btn btn-link" href="{% url 'users:login' %}">Вернуться</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-6 col-lg-4 bg-light p-3 rounded">
                <div class="card shadow-sm">
                    <div class="card-header text-center">
                        <h4 class="card-title">Пароль</h4>
                    </div>
                    <div class="card-body text-center">
                        <form method="post" action="{% url 'users:password_reset' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                                <button class="p-2 btn btn-dark" type="submit">Сбросить пароль</button>
                            </div>
                            <div class="form-group text-center">
                                <a class="btn btn-outline-dark" href="{% url 'users:login' %}">Вернуться</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'blog/base.html' %}


{% block content %}
        <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-lg-12">
                <div class="card shadow-sm my-4">
                    <div class="card-header text-center">
                        <h4 class="card-title">Пользователь</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div class="form-group text-center">
                                <a href="{% url 'blog:home' %}"
                                   class="btn btn-secondary mt-3">Отменить</a>
                                <button class="btn btn-success mt-3" type="submit">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>

        .card {
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
            width: 100%;

        }

        .card-body form {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
        }

        .form-group {
            margin-bottom: 1rem;
            text-align: left;
            padding: 0 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: bold;
        }

        .form-group input[type="email"]:focus,
        .form-group input[type="text"]:focus,
        .form-group input[type="text"]:focus {
            outline: none;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        }

        .form-group input[type="email"],
        .form-group input[type="text"],
        .form-group input[type="text"] {
            padding: 0.5rem;
            border: none;
            border-radius: 5px;
            background-color: #f1f1f1;
            margin-bottom: 0.5rem;
            width: 100%;
            box-sizing: border-box;
        }

        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}