blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (
    HomePageView,
    BlogListView,
    BlogCreateView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
    toggle_activity,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("blog/", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("blog/create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<slug:slug>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/update/<slug:slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/delete/<slug:slug>/", BlogDeleteView.as_view(), name="blog_delete"),
    path("blog/toggle_activity/<slug:slug>/", toggle_activity, name="toggle_activity"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
    path("subscriptions/", include("subsciptions.urls", namespace="subscriptions")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

subsciptions/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from subsciptions.apps import SubsciptionsConfig
from subsciptions.views import (
    SubscriptionDeleteView,
    SubscriptionListView,
    CancelView,
    SuccessView,
    CreateCheckoutSessionView,
    BlogCheckoutPageView,
    StripeIntentView,
    stripe_webhook,
    SubscriptionCreateView,
)

app_name = SubsciptionsConfig.name


urlpatterns = [
    path(
        "subscription-create/<slug:slug>/",
        SubscriptionCreateView.as_view(),
        name="subscription_create",
    ),
    path(
        "subscription-cancel/<slug:slug>/",
        SubscriptionDeleteView.as_view(),
        name="subscription_delete",
    ),
    path(
        "subscription-list/",
        cache_page(60)(SubscriptionListView.as_view()),
        name="subscription_list",
    ),
    path("cancel/", CancelView.as_view(), name="cancel"),
    path("success/<slug:slug>/", SuccessView.as_view(), name="success"),
    path(
        "create-checkout-session/<slug:slug>/",
        CreateCheckoutSessionView.as_view(),
        name="create-checkout-session",
    ),
    path("", BlogCheckoutPageView.as_view(), name="checkout-page"),
    path(
        "create-payment-intent/<int:pk>/",
        StripeIntentView.as_view(),
        name="create-payment-intent",
    ),
    path("webhooks/stripe/", stripe_webhook, name="stripe-webhook"),
]

subsciptions/models.py
from django.db import models

from blog.models import Blog, NULLABLE
from users.models import User


# Create your models here.


class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="User")
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name="Blog")
    status = models.BooleanField(default=False, verbose_name="Status")
    payment_status = models.BooleanField(default=False, verbose_name="Payment status")
    payment_date = models.DateTimeField(
        auto_now=True, verbose_name="Payment date", **NULLABLE
    )

    class Meta:
        verbose_name = "Subscription"
        verbose_name_plural = "Subscriptions"

    def __str__(self):
        return f"{self.user} - {self.blog}: {self.status}"

subsciptions/forms.py
from django import forms
from django.utils import timezone
from blog.forms import StyleFormMixin
from subsciptions.models import Subscription


class SubscriptionForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для оформления подписки.
    fields (list): Список полей формы (пустой, так как все поля заполняются в методе create_subscription).

    Methods:
        create_subscription(user, blog): Создает подписку и сохраняет в базу данных.
    """

    class Meta:
        model = Subscription
        fields = []

    def create_subscription(self, user, blog):
        """
        Создает и сохраняет подписку в базу данных.

        Args:
            user (User): Пользователь, оформляющий подписку.
            blog (Blog): Контент, на который оформляется подписка.
        """
        subscription = self.save(commit=False)
        subscription.user = user
        subscription.blog = blog
        subscription.status = True
        subscription.payment_status = True
        subscription.payment_date = timezone.now()
        subscription.save()

subsciptions/views.py
import json
import stripe
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DeleteView, ListView, TemplateView, CreateView
from blog.models import Blog
from subsciptions.forms import SubscriptionForm
from subsciptions.models import Subscription
from users.models import User


stripe.api_key = settings.STRIPE_SECRET_KEY
YOUR_DOMAIN = "http://127.0.0.1:8000"


class BlogCheckoutPageView(TemplateView):
    """
    Контроллер для страницы оформления подписки на блог.

    Attributes:
        template_name (str): Имя шаблона страницы оформления подписки.
    """

    template_name = " subsciptions/checkout.html"

    def get_context_data(self, **kwargs):
        """
        Получает данные контекста.

        Args:
            **kwargs: Дополнительные аргументы.

        Returns:
            dict: Словарь с данными контекста.
        """

        blog = get_object_or_404(Blog, slug=self.kwargs["slug"])
        context = super(BlogCheckoutPageView, self).get_context_data(**kwargs)
        context.update({"blog": blog, "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY})
        return context


class CreateCheckoutSessionView(View):
    """
    Контроллер для создания сессии оформления подписки.

    Methods:
        post(request, *args, **kwargs): Обрабатывает POST-запрос, создает сессию оформления подписки.
    """

    def post(self, request, *args, **kwargs):
        blog = get_object_or_404(Blog, slug=self.kwargs["slug"])
        user = self.request.user
        try:
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=["card"],
                line_items=[
                    {
                        "price_data": {
                            "currency": "usd",
                            "unit_amount": blog.price * 100,
                            "product_data": {
                                "name": blog.title,
                            },
                        },
                        "quantity": 1,
                    },
                ],
                mode="payment",
                success_url=YOUR_DOMAIN
                + reverse("subsciptions:success", kwargs={"slug": blog.slug}),
                cancel_url=YOUR_DOMAIN + reverse("subsciptions:cancel"),
                metadata={"blog_slug": blog.slug, "user_id": user.pk},
            )
        except Exception as e:
            return JsonResponse({"error": str(e)})

        return redirect(checkout_session.url, code=303)


class CancelView(TemplateView):
    """
    Контроллер для отмены подписки.

    Attributes:
        template_name (str): Имя шаблона страницы отмены подписки.
    """

    template_name = "subsciptions/cancel.html"


class SuccessView(TemplateView):
    """
    Контроллер для успешной оплаты и активации подписки.

    Attributes:
        template_name (str): Имя шаблона страницы успешной оплаты и активации подписки.
    Methods:
        get(request, *args, **kwargs): Обрабатывает GET-запрос, активирует подписку.
    """

    template_name = "subsciptions/success.html"

    def get(self, request, *args, **kwargs):
        blog = get_object_or_404(Blog, slug=self.kwargs["slug"])
        user = self.request.user

        # Создаем подписку для пользователя и связываем с контентом (блогом)
        Subscription.objects.create(
            user=user,
            blog=blog,
            status=True,
            payment_status=True,
            payment_date=timezone.now(),
        )
        return render(request, "subsciptions/success.html")


@csrf_exempt
def stripe_webhook(request):
    """
    Обработчик событий от Stripe.

    Args:
        request: Запрос события от Stripe.

    Returns:
        HttpResponse: Ответ.
    """

    payload = request.body
    event = None

    try:
        event = stripe.Event.construct_from(json.loads(payload), stripe.api_key)
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)

    if event.type == "checkout.session.completed":
        session = event.data.object

        blog_slug = session["metadata"]["blog_slug"]
        user_id = session["metadata"]["user_id"]
        blog = Blog.objects.get(slug=blog_slug)
        user = User.objects.get(pk=user_id)

        Subscription.objects.create(
            user=user,
            blog=blog,
            status=True,
            payment_status=True,
            payment_date=timezone.now(),
        )
        # Отправляем сообщение о подписке
        print(
            f"Payment succeeded for blog: {blog.title}. User phone: {request.user.phone}"
        )

    return HttpResponse(status=200)


class StripeIntentView(View):
    """
    Контроллер для создания намерения оплаты.

    Methods:
         post(request, *args, **kwargs): Обрабатывает POST-запрос, создает намерение оплаты.
    """

    def post(self, request, *args, **kwargs):
        try:
            req_json = json.loads(request.body)
            customer = stripe.Customer.create(phone=req_json["phone"])
            blog_slug = req_json["blog_slug"]
            user = self.request.user
            blog = get_object_or_404(Blog, slug=blog_slug)

            intent = stripe.PaymentIntent.create(
                amount=blog.price,
                currency="usd",
                customer=customer["id"],
                metadata={"blog_slug": blog.slug, "user_id": user.pk},
            )
            Subscription.objects.create(
                user=user,
                blog=blog,
                status=True,
                payment_status=True,
                payment_date=timezone.now(),
            )

            # Выводим сообщение об успешной оплате
            messages.success(
                request, "Оплата успешно проведена. Ваша подписка активирована!"
            )

            return JsonResponse({"clientSecret": intent["client_secret"]})
        except Exception as e:
            return JsonResponse({"error": str(e)})


class SubscriptionCreateView(CreateView):
    """
    Контроллер для создания подписки.

    Attributes:
        model: Модель Subscription.
        template_name (str): Имя шаблона формы создания подписки.
        success_url (str): URL перенаправления после успешного создания подписки.
        form_class: Форма создания подписки.
    """

    model = Subscription
    template_name = "subsciptions/subscription_form.html"
    success_url = reverse_lazy("blog:home")
    form_class = SubscriptionForm

    def form_valid(self, form):
        """
        Проверка валидности формы и создание подписки.
        """

        blog = get_object_or_404(Blog, slug=self.kwargs["slug"])
        form.create_subscription(self.request.user, blog)

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Получает данные контекста.
        """
        context = super().get_context_data(**kwargs)
        blog = get_object_or_404(Blog, slug=self.kwargs["slug"])
        context["blog"] = blog
        return context


class SubscriptionListView(ListView):
    """
    Контроллер для списка подписок пользователя.

    Attributes:
        model: Модель Subscription.
        template_name (str): Имя шаблона списка подписок.
    """

    model = Subscription
    template_name = (
        "subsciptions/subscription_list.html"  # Создайте шаблон для списка подписок
    )

    def get_queryset(self):
        """
        Получает список подписок пользователя.

        Returns:
            QuerySet: QuerySet с подписками.
        """
        user = self.request.user

        # Получаем ID блогов, на которые подписан текущий пользователь
        subscribed_blog_ids = Subscription.objects.filter(
            user=user, status=True
        ).values_list("blog__id", flat=True)

        # Получаем опубликованные блоги, на которые подписан текущий пользователь
        subscribed_blogs = Blog.objects.filter(
            id__in=subscribed_blog_ids, published_on=True
        )

        # Получаем блоги, созданные текущим пользователем и опубликованные
        user_blogs = Blog.objects.filter(user=user, published_on=True)

        # Получаем блоги, созданные текущим пользователем, но неопубликованные
        user_unpublished_blogs = Blog.objects.filter(user=user, published_on=False)

        # Объединяем все полученные блоги и убираем возможные дубликаты
        combined_blogs = (
            user_blogs | subscribed_blogs | user_unpublished_blogs
        ).distinct()

        return combined_blogs


class SubscriptionDeleteView(DeleteView):
    """
    Контроллер для удаления подписки.

    Attributes:
        model: Модель Subscription.
        template_name (str): Имя шаблона подтверждения удаления подписки.
        success_url (str): URL перенаправления после успешного удаления подписки.

    """

    model = Subscription
    template_name = "subsciptions/subscription_confirm_delete.html"
    success_url = reverse_lazy("blog:home")

    def get_queryset(self):
        """
        Получает QuerySet подписок пользователя.

        Returns:
            QuerySet: QuerySet подписок пользователя.
        """
        return Subscription.objects.filter(user=self.request.user)

    def get_object(self, queryset=None):
        """
        Получает объект подписки.

        Args:
            queryset: QuerySet подписок.

        Returns:
            object: Объект подписки.
        """
        return get_object_or_404(self.get_queryset(), blog__slug=self.kwargs["slug"])

subsciptions/templates/subsciptions/cancel.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

subsciptions/templates/subsciptions/checkout.html
{% extends 'blog/base.html' %}
{% block content %}
  <head>
    <title>Buy cool new product</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://js.stripe.com/v3/"></script>
    <head>
    <title>Buy cool new product</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <style>
    * {
  box-sizing: border-box;
}
body {
  font-family: -apple-system, BlinkMacSystemFont, sans-serif;
  font-size: 16px;
  -webkit-font-smoothing: antialiased;
  display: flex;
  justify-content: center;
  align-content: center;
  height: 100vh;
  width: 100vw;
}
form {
  width: 30vw;
  min-width: 500px;
  align-self: center;
  box-shadow: 0px 0px 0px 0.5px rgba(50, 50, 93, 0.1),
    0px 2px 5px 0px rgba(50, 50, 93, 0.1), 0px 1px 1.5px 0px rgba(0, 0, 0, 0.07);
  border-radius: 7px;
  padding: 40px;
}
input {
  border-radius: 6px;
  margin-bottom: 6px;
  padding: 12px;
  border: 1px solid rgba(50, 50, 93, 0.1);
  height: 44px;
  font-size: 16px;
  width: 100%;
  background: white;
}
.result-message {
  line-height: 22px;
  font-size: 16px;
}
.result-message a {
  color: rgb(89, 111, 214);
  font-weight: 600;
  text-decoration: none;
}
.hidden {
  display: none;
}
#card-error {
  color: rgb(105, 115, 134);
  text-align: left;
  font-size: 13px;
  line-height: 17px;
  margin-top: 12px;
}
#card-element {
  border-radius: 4px 4px 0 0 ;
  padding: 12px;
  border: 1px solid rgba(50, 50, 93, 0.1);
  height: 44px;
  width: 100%;
  background: white;
}
#payment-request-button {
  margin-bottom: 32px;
}
/* Buttons and links */
button {
  background: #5469d4;
  color: #ffffff;
  font-family: Arial, sans-serif;
  border-radius: 0 0 4px 4px;
  border: 0;
  padding: 12px 16px;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  display: block;
  transition: all 0.2s ease;
  box-shadow: 0px 4px 5.5px 0px rgba(0, 0, 0, 0.07);
  width: 100%;
}
button:hover {
  filter: contrast(115%);
}
button:disabled {
  opacity: 0.5;
  cursor: default;
}
/* spinner/processing state, errors */
.spinner,
.spinner:before,
.spinner:after {
  border-radius: 50%;
}
.spinner {
  color: #ffffff;
  font-size: 22px;
  text-indent: -99999px;
  margin: 0px auto;
  position: relative;
  width: 20px;
  height: 20px;
  box-shadow: inset 0 0 0 2px;
  -webkit-transform: translateZ(0);
  -ms-transform: translateZ(0);
  transform: translateZ(0);
}
.spinner:before,
.spinner:after {
  position: absolute;
  content: "";
}
.spinner:before {
  width: 10.4px;
  height: 20.4px;
  background: #5469d4;
  border-radius: 20.4px 0 0 20.4px;
  top: -0.2px;
  left: -0.2px;
  -webkit-transform-origin: 10.4px 10.2px;
  transform-origin: 10.4px 10.2px;
  -webkit-animation: loading 2s infinite ease 1.5s;
  animation: loading 2s infinite ease 1.5s;
}
.spinner:after {
  width: 10.4px;
  height: 10.2px;
  background: #5469d4;
  border-radius: 0 10.2px 10.2px 0;
  top: -0.1px;
  left: 10.2px;
  -webkit-transform-origin: 0px 10.2px;
  transform-origin: 0px 10.2px;
  -webkit-animation: loading 2s infinite ease;
  animation: loading 2s infinite ease;
}
@-webkit-keyframes loading {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
@keyframes loading {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
@media only screen and (max-width: 600px) {
  form {
    width: 80vw;
  }
}
    </style>
  </head>
  <body>
    <section>
      <div class="product">
        {% comment %}
        <img src="https://i.imgur.com/EHyR2nP.png" alt="The cover of Stubborn Attachments" />
        {% endcomment %}
        <div class="description">
          <h3>{{blog.title}}</h3>
          <h5>${{ blog.get_display_price }}</h5>
        </div>
     </div>
      <button type="button" id="checkout-button">Checkout</button>
      <hr />
      <h2>Checkout using custom payment flow</h2>
      <form id="payment-form">
        <input type="text" id="phone" placeholder="Номер телефона" />
        <div id="card-element"><!--Stripe.js injects the Card Element--></div>
        <button id="submit">
          <div class="spinner hidden" id="spinner"></div>
          <span id="button-text">Pay</span>
        </button>
        <p id="card-error" role="alert"></p>
        <p class="result-message hidden">
          Payment succeeded, see the result in your
          <a href="" target="_blank">Stripe dashboard.</a> Refresh the page to pay again.
        </p>
      </form>
    </section>
    {% csrf_token %}
  </body>
  <script type="text/javascript">
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {
      fetch("{% url 'subscriptions:create-checkout-session' blog.slug %}", {
        method: "POST",
        headers: {
            'X-CSRFToken': csrftoken
        }
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (session) {
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
    });

    // Disable the button until we have Stripe set up on the page
    document.querySelector("button").disabled = true;

    var elements = stripe.elements();
    var style = {
      base: {
        color: "#32325d",
        fontFamily: 'Arial, sans-serif',
        fontSmoothing: "antialiased",
        fontSize: "16px",
        "::placeholder": {
          color: "#32325d"
        }
      },
      invalid: {
        fontFamily: 'Arial, sans-serif',
        color: "#fa755a",
        iconColor: "#fa755a"
      }
    };
    var card = elements.create("card", { style: style });
    // Stripe injects an iframe into the DOM
    card.mount("#card-element");
    card.on("change", function (event) {
      // Disable the Pay button if there are no card details in the Element
      document.querySelector("button").disabled = event.empty;
      document.querySelector("#card-error").textContent = event.error ? event.error.message : "";
    });
    var form = document.getElementById("payment-form");
    form.addEventListener("submit", function(event) {
      event.preventDefault();
      // Complete payment when the submit button is clicked
      fetch("{% url 'subscriptions:create-payment-intent' blog.slug %}", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          'X-CSRFToken': csrftoken
        },
        body: JSON.stringify({
          phone: document.getElementById('phone').value
        })
      })
        .then(function(result) {
          return result.json();
        })
        .then(function(data) {
          payWithCard(stripe, card, data.clientSecret);
        });
    });

    // Calls stripe.confirmCardPayment
    // If the card requires authentication Stripe shows a pop-up modal to
    // prompt the user to enter authentication details without leaving your page.
    var payWithCard = function(stripe, card, clientSecret) {
      loading(true);
      stripe
        .confirmCardPayment(clientSecret, {
          payment_method: {
            card: card
          }
        })
        .then(function(result) {
          if (result.error) {
            // Show error to your customer
            showError(result.error.message);
          } else {
            // The payment succeeded!
            orderComplete(result.paymentIntent.id);
          }
        });
    };
    /* ------- UI helpers ------- */
    // Shows a success message when the payment is complete
    var orderComplete = function(paymentIntentId) {
      loading(false);
      document
        .querySelector(".result-message a")
        .setAttribute(
          "href",
          "https://dashboard.stripe.com/test/payments/" + paymentIntentId
        );
      document.querySelector(".result-message").classList.remove("hidden");
      document.querySelector("button").disabled = true;
    };
    // Show the customer the error from Stripe if their card fails to charge
    var showError = function(errorMsgText) {
      loading(false);
      var errorMsg = document.querySelector("#card-error");
      errorMsg.textContent = errorMsgText;
      setTimeout(function() {
        errorMsg.textContent = "";
      }, 4000);
    };
    // Show a spinner on payment submission
    var loading = function(isLoading) {
      if (isLoading) {
        // Disable the button and show a spinner
        document.querySelector("button").disabled = true;
        document.querySelector("#spinner").classList.remove("hidden");
        document.querySelector("#button-text").classList.add("hidden");
      } else {
        document.querySelector("button").disabled = false;
        document.querySelector("#spinner").classList.add("hidden");
        document.querySelector("#button-text").classList.remove("hidden");
      }
    };

  </script>

{% endblock %}

subsciptions/templates/subsciptions/subscription_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mt-4 mb-4 text-center">Подтверждение отмены подписки</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body text-center">
                    <form method="post" enctype="multipart/form-data" class="mt-3">
                        {% csrf_token %}
                        <p>
                            <strong>Вы уверены, что хотите отменить подписку на блог "{{ subscription.blog.title}}"?</strong>
                        </p>
                        <div class="row justify-content-center">
                            <button type="submit" class="btn btn-danger">Да, отменить подписку</button>
                            <a href="{% url 'blog:home' %}" class="btn btn-secondary">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .card {
        border: 1px solid #ddd;
        border-radius: 5px;
        box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
        width: 100%;

    }

    .btn {
        padding: 10px 20px;
        border-radius: 20px;
        cursor: pointer;
        transition: all 0.3s ease-in-out;
    }

    .btn:hover {
        transform: translateY(-3px);
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
    }

    .btn:active {
        transform: translateY(-1px);
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }
</style>
{% endblock %}

subsciptions/templates/subsciptions/subscription_list.html
{% extends 'blog/base.html' %}

{% block content %}
{% load my_tags %}

<div class="container" style="text-align: center">
    <h2>Список подписок</h2>
</div>

<div class="card flex-md-row mb-4 box-shadow h-md-250">
    <div class="card-body d-flex flex-column align-items-start">
        <div class="card-subtitle mb-4" id="blog-list">
            {% for object in object_list %}
            {% if object.published_on or object.user == user %}

            <div class="mb-5">
                <h3 class="text-center">
                    <a class="text-dark" href="{% url 'blog:blog_detail' object.slug %}">{{ object.title }}</a>
                </h3>

                <p class="card-text text-center">{{ object.description | truncatechars:100 }}</p>

                <div class="text-center">
                    <img src="{% mediapath object.image %}"
                         class="card-img-top mx-auto d-block img-fluid"
                         alt=""
                         style="width: auto; max-height: 300px;">
                </div>

                <h3 style="text-align: center">Просмотры: {{ object.views }}</h3>

                <div class="text-center mt-3">
                    <a href="{% url 'blog:blog_detail' object.slug %}" class="btn btn-info btn-sm">Перейти к записи</a>
                </div>

                <div class="text-center mt-3">
                    {% if user.is_authenticated and object.user != user %}
                    <a href="{% url 'subscriptions:subscription_delete' object.slug %}" class="btn btn-danger btn-sm">Отписаться</a>
                    {% endif %}
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

<style>
    .btn {
        padding: 10px 20px;
        border-radius: 20px;
        cursor: pointer;
        transition: all 0.3s ease-in-out;
    }

    .btn:hover {
        transform: translateY(-3px);
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
    }

    .btn:active {
        transform: translateY(-1px);
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }
</style>

{% endblock %}

subsciptions/templates/subsciptions/success.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="container mt-4">
    <h2 class="mt-4 mb-4 text-center">Оплата прошла успешно!</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body text-center">
                    <p class="active">
                        <strong>Мы ценим ваш бизнес! Если у Вас возникли вопросы, пожалуйста, пишите на электронную почту</strong>
                    </p>

                    <div class="row justify-content-center">
                        <a class="btn btn-outline-link" >example@yandex.ru</a>
                    </div>
                    <div class="row justify-content-center">
                        <a class="btn btn-dark" href="{% url 'blog:home' %}">Вернуться на главную</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .card {
        border: 1px solid #ddd;
        border-radius: 5px;
        box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
        width: 100%;

    }

    .btn {
        padding: 10px 20px;
        border-radius: 20px;
        cursor: pointer;
        transition: all 0.3s ease-in-out;
    }

    .btn:hover {
        transform: translateY(-3px);
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
    }

    .btn:active {
        transform: translateY(-1px);
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }
</style>

{% endblock %}